#!/bin/bash
read=0
while read line; do
  if [ "${line#BLOCKS:}" != "$line" ]; then read=1; continue; fi
  if [ "${line#EXTENTS:}" != "$line" ]; then read=1; continue; fi
  [ "${line#debugfs:}" != "$line" ] && read=0
  [ "${line#TOTAL:}" != "$line" ] && read=0
  [[ read -ne 0 ]] && echo "$line"
done | sed 's#([^)]*):##g;s#, #\n#g'
